<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MD-5Q0H9F2" failures="2" tests="9" name="RetryMultipleTestCases" time="0.098" errors="0" timestamp="2021-07-21T13:01:16 IST">
  <testcase classname="TestPackage.RetryLogic" name="Test1" time="0.011">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="TestPackage.RetryLogic" name="Test1" time="0.003">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="TestPackage.RetryLogic" name="Test1" time="0.002">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="TestPackage.RetryLogic" name="Test1" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TestPackage.RetryLogic.Test1(RetryLogic.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="TestPackage.RetryLogic" name="Test2" time="0.001">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="TestPackage.RetryLogic" name="Test2" time="0.001">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="TestPackage.RetryLogic" name="Test2" time="0.005">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="TestPackage.RetryLogic" name="Test2" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TestPackage.RetryLogic.Test2(RetryLogic.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase classname="TestPackage.RetryLogic" name="Test3" time="0.002"/>
</testsuite> <!-- RetryMultipleTestCases -->
